### ISSUE TITLE
I have a more or less working version

### ISSUE THREAD

**Issue by fhars** [mikewarot/stoical#2]
Hi, I got it to compile and mostly working on Ubuntu 20.04 with GCC 9.4, maybe you want to take a look at it: https://github.com/fhars/stoical

**Comment by mikewarot** [comment]
It works for me under Ubutno 20.4 LTS, with one missing file (README) causing a minor error.

I'm not at a loss as to how to merge this in, as this is all new to me.

**Comment by saxbophone** [comment]
Thanks @fhars, I applied your patch to my copy here. Interestingly, with your patch applied, all my "tests" run with no errors at all on macOS, but not on Linux... https://github.com/saxbophone/stoical/pull/2

I have a feeling there is more funny business going on particularly with the threads —I had to fix more occurrences of the code trying to pass a pointer into a float (maybe I got those errors and you didn't because you're not building with threads?).

**Comment by mikewarot** [comment]
@fhars - Thanks, I've pulled all of the changes you made into this repository, and started the work of getting it in shape. Thanks again for your help in this.
